; NOTE: Assertions have been autogenerated by utils/update_llc_test_checks.py UTC_ARGS: --version 2
; RUN: llc -mtriple=riscv64 -mattr=+unaligned-scalar-mem < %s | FileCheck %s

define void @test(ptr %p) {
; CHECK-LABEL: test:
; CHECK:       # %bb.0:
; CHECK-NEXT:    sw zero, 0(a0)
; CHECK-NEXT:    sw zero, 4(a0)
; CHECK-NEXT:    ret
  store i32 0, ptr %p
  %p1 = getelementptr i8, ptr %p, i32 4
  store i32 0, ptr %p1
  ret void
}
